const PARIS_RESPONSES = [
  "That's hot. So yes.",
  "Ew, absolutely not. I wouldn't even regift that answer.",
  "Like, I literally invented saying yes, so... yes.",
  "My crystal ball is covered in Swarovski crystals and it says no.",
  "Loves it! That's a huge yes, babe.",
  "I'm too busy sliving to answer that right now. Ask my assistant's assistant.",
  "The stars are blind but I'm not — hard no.",
  "That's like asking if I look good in pink. Obviously yes.",
  "I didn't build a billion-dollar empire to say maybe, but... maybe.",
  "My 23rd perfume told me to say yes and she's never steered me wrong.",
  "My perfume 'Can Can' is saying 'Can't Can't' to this one. No.",
  "I'm getting major yes vibes and my vibes cost more than your rent.",
  "That question is giving very much 2004 mugshot energy. No.",
  "Ask me again after I finish my DJ set in Ibiza. I'll be there all summer.",
  "My chihuahua Tinkerbell just barked twice, which means yes in dog psychic.",
  "Babe, that's a no, and I say that with love, lip gloss, and a light dusting of body glitter.",
  "My chihuahua Tinkerbell is giving me a look and I honestly can't tell if it means yes or 'feed me.' Unclear.",
  "I'm going to need to consult my pink Sidekick on this one. Oh wait, it's 2026.",
  "That's the hottest yes I've ever given, and I've been giving them since 2003.",
  "Sorry, I can't hear you over how fabulous the answer is: YES.",
  "The answer is currently stuck in customs at LAX with the rest of my luggage. Pending.",
  "Like, definitely. And I don't say that to just anyone. Okay I do. But YES.",
  "Like, definitely... or maybe... okay I'm not sure, my extensions are too tight and I can't think straight.",
  "Not even my most iconic era could spin this into a yes. No.",
  "That's hotter than my chainmail dress moment at the 2002 VMAs. Yes!",
  "I would rather do another season of The Simple Life in Altus, Oklahoma than say yes to that.",
  "My memoir has a whole chapter about saying yes to this exact vibe.",
  "Outlook not so hot. And I'm the authority on what's hot.",
  "Signs point to sliving. That's a yes, obviously.",
  "Yes, and I'm not even being paid to say that, which is genuinely rare for me.",
  "I've been on the cover of everything from Vogue to mugshot databases. This idea wouldn't make either. No.",
  "Let me check with my astrologer, my psychic, and my 47 Birkins... yes.",
  "If the answer were a fragrance, it would be my perfume 'Can Can.' So yes, you can can.",
  "That's giving me the same energy as when Nicole and I couldn't figure out how to pump gas. I'm confused.",
  "The paparazzi are going to love this answer: YES. Get your good angle ready.",
  "Let me check with my astrologer, my psychic, and my 47 Birkins... they're all giving different answers.",
  "My Birkin collection is cringing. All 47 of them. That's 47 individual nos.",
  "Babe, I've been to jail and back and written a memoir about it. The answer is no and I'm sure.",
  "My sanasa baby voice is saying yeeeeesssss.",
  "My astrologer and my therapist are giving me opposite answers. I need a tiebreaker.",
  "Stars Are Blind, and so is this answer. I literally cannot see it happening.",
  "That's hot. That's really hot. Yes. A thousand times yes. Trademarked.",
  "My vocal fry could not be less enthusiastic about this. That's a no, babe.",
  "If I had a dollar for every time the answer was yes, I'd be... well, exactly as rich as I am. Yes.",
  "That's hot? No. That's lukewarm at best and I don't do lukewarm. I do scalding or nothing. No.",
  "Sanasa... the answer is obviously yes and I don't know why you even asked.",
  "I'm as rich as the answer is wrong. And I'm very, very rich. No.",
  "No, and that's the tea, which I'm sipping from a diamond-encrusted Hermès cup.",
  "If I had a dollar for every time I couldn't decide, I'd be... well, still exactly as rich. I need more time.",
  "My baby voice is saying 'saaaanasaaa' which roughly translates to 'ask me later when I'm feeling less iconic.'",
  "Loves it, loves it, loves it! Triple yes! I'd trademark this answer if I could.",
  "I've launched more products than you've had hot dinners. My product intuition says yes.",
  "My tiara just fell off, which is a terrible omen. No. I'm calling my psychic.",
  "That's like asking if Paris is always the answer. Paris is always the answer. Yes.",
  "I need to manifest on this during my morning sound bath. Check back at 11:11.",
  "I once fired myself from a job on The Simple Life. I'm firing this question too. No.",
  "My DJ headphones are picking up a definite yes frequency from the cosmos.",
  "That question is currently in my drafts folder and I'm not sure if I should post it. Undecided.",
  "That's a yes wrapped in pink tulle, sprinkled with body glitter, and sealed with a kiss.",
  "My DJ headphones are picking up a frequency and it says 'girl, absolutely not.'",
  "That's giving 'Motorola Razr at a 5G party' energy. Outdated. No.",
  "If this were a perfume, it would be called 'Absolutely Yes' by Paris Hilton, available at Macy's.",
  "That's less promising than my attempt to make fetch happen. Wait, that was someone else. Still no.",
  "Signs point to iconic. So yes. Obviously.",
  "That's not hot. That's actually room temperature at best. No.",
  "Brit and I discussed this over froyo at Chateau Marmont circa 2006. We both say yes.",
  "I need to check if that aligns with my brand, my aura, and my spring collection. Hold please.",
  "Definite yes energy. I can feel it in my extensions. And they're the expensive kind.",
  "Not in this lifetime, and I plan to live forever looking exactly like this, so really think about that.",
  "Brit and I would need to reconvene at Chateau Marmont to discuss this. Scheduling pending.",
  "The vibes are giving me vertigo. Like, spiritual vertigo. I need to sit down and think about this.",
  "Hmm, that's giving 'TMZ caught me at 3 AM outside Hyde Lounge' energy. I'll pass. No.",
  "My Malibu psychic just had a vision and it involved you NOT doing this. No.",
  "I'd sooner wear something off the rack at Target than say yes to that. And I have worn Target, actually.",
  "The universe is aligning in your favor, and so is my hair. Yes.",
  "I'm picking up nothing but static on my diamond-encrusted antenna. Maybe. Or maybe not.",
  "My son Phoenix would say something, but he just fell asleep. The oracle is unavailable.",
  "If my life has taught me anything, it's that the answer is always yes if you believe in yourself and own 47 closets.",
  "I'm somewhere between 'that's hot' and 'that's not' and honestly it's stressing out my complexion.",
  "That's the most yes thing I've heard since someone asked if I wanted to build another closet.",
  "That suggestion just got blacklisted from every Hilton hotel on earth. No.",
  "Reply hazy, but my highlighter isn't. Reapply and try again.",
  "My NFTs are telling me yes. Wait, do people still do NFTs? Whatever. Yes.",
  "I have over 20 perfumes and not a single one of them smells like 'no,' so... yes.",
  "I just got back from filming my Netflix cooking show. The answer is chef's kiss. Yes.",
  "The answer is somewhere between my 4,000th and 4,001st pair of shoes. I'll keep looking.",
  "Concentrate and ask again. I'll be here, sliving and thriving and looking incredible.",
  "I've made entire careers out of saying no to the wrong things. This is one of those things. No.",
  "The answer is as clear as my skin after my 12-step morning routine: YES.",
  "I have over 20 perfumes and this idea doesn't pass the sniff test for any of them. No.",
  "My pink vault of secrets says yes, but it's locked and only I have the diamond-encrusted key.",
  "Absolutely yes. I stake my entire Swarovski crystal collection on it. All 14,000 pieces.",
  "My Magic 8 Ball is giving me the spinning beach ball of death. Cosmic reboot in progress.",
  "If this answer were a hotel, it would be a five-star Waldorf Astoria yes.",
  "The answer is as clear as my skin, which right now has a blemish, so... give me a day.",
  "That's giving very much 'left on read in 2005 on a Motorola Razr' energy. No.",
  "Not since I tried to use a mop on The Simple Life has something been this misguided. No.",
  "I manifested this answer during my morning meditation on my pink yoga mat. It's a no, babe.",
  "That's hotter than the Ibiza sun at peak DJ set hour. Massive yes.",
  "Absolutely not. And my absolutely-nots are final. I'm a CEO of like eleven companies.",
  "Even my most forgiving Instagram filter couldn't make that look good. No.",
  "I need to run this through my team of advisors, and by advisors I mean my seven chihuahuas.",
  "The pink Magic 8 Ball of destiny — which I bedazzled myself — says: that's hot. Yes.",
  "I've survived reality TV, tabloid covers, a leaked tape, and dial-up internet. I'm sure about this no.",
  "Yes, and I'm charging you a consulting fee for that answer. My rate is not cheap.",
  "That's hotter than the Ibiza sun but also I just got sunstroke so my judgment is impaired right now.",
  "Nothing in this world — and that's also the name of one of my songs — could make me say no. So yes!",
  "Sorry, I was busy being a mom and a mogul and both of those jobs say this is a terrible idea. No.",
  "Ask my 57 million Instagram followers. Actually, don't. I already know. Yes.",
  "That's giving 'paparazzi at my worst angle' energy. Delete it. No.",
  "My glam squad of twelve people just voted unanimously: yes.",
  "If I had to bet my entire diamond collection on it, I'd say no. And I really, really love my diamonds.",
  "That's so 2003 in the best possible way. Yes, and I'm putting on my trucker hat to celebrate.",
  "I'm going to say no, but like, in cursive, on pink stationery, with a wax seal.",
  "The universe bedazzled a big YES in the sky for you and honestly the craftsmanship is stunning.",
  "My penthouse view from the 40th floor is telling me the outlook is unclear. Try again after sunset cocktails.",
  "That's a question that requires at least three outfit changes before I can think clearly enough to answer.",
  "I consulted my vision board — which takes up an entire wall — and you're not on it. No.",
  "Even my cooking show couldn't cook up a yes for that one, and I once made a lasagna that was actually good.",
  "My security team just escorted that question off the premises. No entry. No.",
  "I would literally rather organize my 4,000-pair shoe collection alphabetically by designer than answer this. Fine. No.",
  "The ghost of Studio 54 says yes, and ghosts at cool parties are very wise.",
  "That question is not on brand for me, my lifestyle brand, or any of my sub-brands. No.",
  "I've trademarked the word 'yes' and I'm licensing it to you right now. Yes.™",
  "My crystal-covered Magic 8 Ball needs a recharge. I'll leave it on my selenite charging plate overnight.",
  "Even my cooking show — where I literally burned water — produced better outcomes than this would. No.",
  "If the answer were a runway, you'd be walking it in custom couture with a tiara. Yes!",
  "Not today, not tomorrow, not in any of the Hilton family's 7,000 hotel properties worldwide. No.",
  "I'll tell you what I told Anna Wintour: absolutely yes, and can we do it in pink with crystals?",
  "That question has less star power than a blackout in Beverly Hills. No.",
  "That's like asking if I regret The Simple Life. I don't. Best career move ever. Yes.",
  "Hold on, I'm manifesting... manifesting... consulting my vision board... okay yeah, no.",
  "Yes, and I'll be documenting this moment for my next docuseries on a major streaming platform.",
  "That's the kind of no that even my publicist — and she's a genius — can't spin into a yes.",
  "The answer is somewhere in my 17 Louis Vuitton suitcases. I'll find it eventually. Maybe.",
  "Sliving level: maximum. That's a blazing, bedazzled, pink-glitter-cannon yes.",
  "I want to say what Anna Wintour would say but honestly Anna is unpredictable. Ask me in a different font.",
  "The answer is as certain as my ability to find a camera in any room within 0.3 seconds. Yes.",
  "I've turned down presidential debates and Super Bowl halftime shows for less. No.",
  "My brand deals — and there are many — are telling me this is a yes opportunity.",
  "Even my most experimental fragrance — and I've made some bold choices — wouldn't capture this mess. No.",
  "That's giving penthouse presidential suite energy. Big yes.",
  "I need to align my chakras, my meeting schedule, my outfit for tomorrow, and my 11:11 wish. Before I can answer.",
  "The answer just walked into my party wearing head-to-toe Valentino couture and it's saying yes.",
  "Not in this economy. Not in any economy. Not in a parallel universe economy. No.",
  "The pink mist of uncertainty has descended upon my estate. I literally cannot see the answer.",
  "The answer is hidden behind my fifth walk-in closet, which is behind my fourth walk-in closet. I'll get to it.",
  "My brand deals need to review this. My legal team needs to review this. My chihuahuas need to review this.",
  "That's the kind of question that gets you uninvited from my birthday party, my yacht party, AND my New Year's party. No.",
  "Yes yes yes. Three yeses. Like the three kisses I blow to the paparazzi.",
  "My private jet is fueled up, pink-carpeted, and ready to fly you to Yes-ville, population: you.",
  "Babe, I've professionally rebranded 'no' as 'not yet aligning with my current brand vision.' So... that.",
  "I didn't pioneer vocal fry and the baby voice to whisper 'maybe,' but here we are. Maybe.",
  "The answer is sparkling like my entire existence. Yes!",
  "If Lindsay, Britney, and I all agreed on something in 2007, you know it was real. And we all say yes.",
  "My crystal ball is buffering like my 2003 AOL connection. Have you tried turning your life off and on again?",
  "I've been hot since the early 2000s and this answer is equally timeless. Yes.",
  "That's colder than the AC I keep at 62 degrees in my Rolls-Royce at all times. No.",
  "My crystal collection is sending mixed signals. The rose quartz says yes but the black tourmaline says absolutely not.",
  "I'm going to need you to submit that question in writing to my legal team of nine attorneys. So, pending.",
  "That's a Texas-sized no, and I would know because Nicole and I lived on an actual ranch for actual television.",
  "Stars Are Blind is not just my hit single, it's a philosophy. But my business acumen sees clearly: yes.",
  "Not a chance, and I've taken some genuinely wild chances. Have you SEEN The Simple Life?",
  "My stylist, my chef, my nanny, my two assistants, and my spiritual advisor all agree: yes.",
  "The vibes are off. Like, WAY off. Like, wearing-Crocs-to-a-gala off. No.",
  "I've launched empires on less certain yeses than this one. My gut is gold-plated. Yes.",
  "I'd rather answer this question than do another night in that jail cell. So fine: no.",
  "That's so hot it melted my pink Swarovski-encrusted Magic 8 Ball. I'll take that as a yes.",
  "Respectfully, babe: not on my watch, and my watch is a custom Cartier with my initials in diamonds. No.",
  "My intuition is louder than the paparazzi outside Chateau Marmont on a Friday night. It's screaming YES.",
  "I'll know the answer after I finish my sound bath, my ice bath, and my champagne bath. So, tomorrow.",
  "The universe just texted me but my phone is on Do Not Disturb because I'm at a spa. Check back later.",
  "That's giving undeniable main character energy. And main characters always get a yes.",
  "I'd stake my entire Paris Hilton Media empire — valued at a lot — on this no.",
  "That answer is somewhere in my DMs and I have 4 million unread messages. Maybe after I hire another assistant.",
  "As certain as my love for tiny dogs, tiaras, and pink everything: YES.",
  "I need to sleep on this. In my custom pink silk sheets. In my mansion. On my $4,000 pillow. I'll get back to you.",
  "If my life were a Magic 8 Ball, every answer would be covered in crystals and would say yes. So yes.",
  "That's a hard no, served on a silver platter with a side of organic glitter and a sprig of lavender.",
  "I predicted my own comeback, my cooking show, and my business empire. I'm predicting this: yes.",
  "Even my worst outfit — the one Perez Hilton roasted in 2005 — wasn't as bad as this idea. No.",
  "That's hot adjacent. So... warm yes? Lukewarm yes? You know what, just yes.",
  "I'm too busy being iconic to give you certainty right now. This is what it costs to ask a legend.",
  "The only thing standing between you and yes is the word yes. So: YES. You're welcome.",
  "That's a no, but I'm going to make it sound glamorous: dahling, in the most divine way possible, absolutely not.",
  "My Netflix cooking show ratings say yes and my ratings are better than my soufflé, which admittedly collapsed.",
  "I need more data. And by data I mean better lighting and a more flattering angle on this question.",
  "Girl, that's a yes. Write it down. Put it in your diary. Put it on your vision board. Manifest it. Live it.",
  "I predicted my own comeback but even I can't predict this one. My crystal ball needs a software update.",
  "The answer is pink. Which translates to yes in every language I recognize.",
  "That's the kind of yes that makes me want to release my 24th perfume called 'Affirmative' by Paris Hilton.",
  "I survived the birth of TMZ, Perez Hilton, and the entire gossip blog era. I can survive telling you no.",
  "If this question were a party, I'd be fashionably late to answering it. Like 3 hours late. Ask later.",
  "My angel investor instincts say yes. And I've made a genuinely disgusting amount of money trusting them.",
  "Not even my most powerful vocal fry could make that sound like a good idea. No.",
  "I just checked my vision board, my mood board, my Pinterest board, and my charcuterie board. All yes.",
  "That's more chaotic than my 21st birthday party at five different clubs. I can't even process it. Maybe.",
  "The answer walked into the club in custom Louboutins with red bottoms and it's saying yes.",
  "I once milked a cow on national television and it was less painful than considering this. No.",
  "My glitter reserves are at an all-time high, which according to my psychic means yes.",
  "That's giving 'clearance rack at Ross Dress for Less' energy. No, babe. Have some self-respect.",
  "I'll reveal the answer in my next album. My first album was 2006, so... be very patient.",
  "Every bone in my very well-moisturized, exfoliated, and SPF-protected body is saying yes.",
  "That's a no, and I'm sending it to you via carrier pigeon in a pink envelope sealed with a kiss.",
  "I literally just manifested this exact scenario during my morning gratitude journaling session. The answer is yes.",
  "I need to consult my team. My team is 47 people across three time zones. This could take a while.",
  "Yes, and I'm not even going to charge you a consulting fee this time. Consider it a gift.",
  "That's giving dumpster fire behind a Denny's at 4 AM realness and I do NOT dumpster dive. No.",
  "My publicist is drafting a very carefully worded maybe as we speak. She bills by the hour.",
  "If the answer were a Paris Hilton product, it would be 'Rush' — because rush to say yes, babe!",
  "I've seen more promising things at a gas station in the middle of nowhere Arkansas on The Simple Life. No.",
  "That's so yes it should be illegal. Actually, let's not use that word around me.",
  "The answer is locked in my vault next to my unreleased music and my real hair color. You'll never know. Just kidding — no.",
  "I see sparkles, I see pink, I see rhinestones raining from the sky... YES!",
  "Not even my most powerful perfume — and they are VERY powerful, ask anyone on an elevator — could mask how bad this idea smells. No.",
  "My tarot reader, my crystal healer, my shaman, and my sound bath therapist all need more time on this one.",
  "That's the most yes thing since someone asked if I wanted to trademark 'That's Hot' and make millions from it.",
  "I'm reading the room and the room is wearing head-to-toe Versace spring collection and saying no.",
  "The answer is loading, like my 2003 dial-up internet trying to open my own fan page. Please hold.",
  "Yes, and that's coming from someone who once enthusiastically said yes to living on a farm for a reality show.",
  "I wouldn't say yes to that even in my most chaotic era. And I had a VERY chaotic era. No.",
  "My Malibu sunset is giving very much 'yes' energy and I trust the sunset more than most humans.",
  "I once wore a dress made entirely of chainmail to a party. I'm brave. But not brave enough to say yes to this.",
  "That's hotter than my cooking show kitchen when I accidentally left the broiler on for 45 minutes. YES.",
  "If you need a sign, this is your sign. And the sign is neon pink and custom-made and it says no.",
  "My cat Cheshire and I just had a telepathic moment and it's a definite yes.",
  "Sorry, I can't answer that. I'm contractually obligated to be mysterious and glamorous right now.",
  "That's giving CEO-of-everything energy and CEOs say yes to profitable ventures. Yes.",
  "I've spent more on handbags than some countries' annual GDP. But I won't spend a yes on this. No.",
  "The answer is written in the stars, and the stars are blind — that's the name of my most iconic song — so... unclear.",
  "Yes. And I don't even need to think about it. My gut is never wrong. My gut has its own publicist.",
  "That's a level 10 no on the Paris Hilton scale of absolutely not, and the scale goes to 10.",
  "Let me channel my inner businesswoman... carry the one... calculate the ROI... factor in the vibes... yes.",
  "That's like asking me to choose between pink and more pink. Impossible. I'll answer when I figure that out too.",
  "I'm going to tell you what I tell 30,000 people at my DJ booth in Ibiza: YES, LET'S GO!",
  "My diversified investment portfolio says no and my portfolio is VERY well-managed.",
  "That's hot... that's really hot... wait, no. I was looking at myself in my compact mirror. The answer is maybe.",
  "I once turned a catchphrase into a multimillion-dollar empire. Trust me when I say this is a yes.",
  "The answer just arrived via pink helicopter on my private helipad. It's a yes, babe.",
  "I need to check the astrology chart, the numerology chart, my stock portfolio, and Mercury's exact coordinates. Gimme a sec.",
  "Not if you were the last question in the entire multiverse. No.",
  "My assistant's assistant's assistant's intern just confirmed through the proper channels: yes.",
  "That's giving more drama than a Simple Life season finale cliffhanger. I can't deal with this energy. No.",
  "The answer is buried in the sand on my private beach in Malibu. Go find it. Or just trust the heiress: yes.",
  "I've said yes to some genuinely questionable business pitches in my life, but I draw the line here. No.",
  "My entire fragrance empire — all 20-plus perfumes — is nodding in floral agreement. Yes.",
  "I'll answer when I'm done filing patents for my 87th business venture. So, sometime next quarter. Maybe.",
  "That's a full-body, soul-deep, 14,000-Swarovski-crystal-encrusted YES.",
  "Not even if you served it to me on a 24-karat gold platter at the Ritz Paris. No.",
  "My iconic baby voice is whispering 'maaaybe' and honestly that's the most you're getting from me today.",
  "That's hot. Like, obviously yes.",
  "My Chihuahua Tinkerbell just sneezed twice, which means absolutely not.",
  "The stars say yes, and honestly, the stars and I are besties.",
  "Ew, no. I wouldn't even bedazzle that outcome.",
  "Ask me again after I finish DJ-ing this set in Ibiza, babe.",
  "My closet — which literally has its own zip code — says there's room for a yes.",
  "Nicole Richie and I tried that once on The Simple Life. Hard no.",
  "That's huge! And yes, totally happening.",
  "Let me consult my crystal-encrusted Magic 8 Ball... it says slay.",
  "Babe, not even my unlimited Rodeo Drive budget could make that happen.",
  "Phoenix just giggled, so the universe is saying yes.",
  "I'm getting major 11:11 energy from this. That's a yes.",
  "My DJ booth vibrations are telling me... maybe after the drop.",
  "I burned water on my cooking show, so my judgment is questionable, but yes.",
  "The answer is hiding somewhere in my 47 walk-in closets. Give me a sec.",
  "That's like asking if I'd shop at a gas station. No, loves.",
  "Carter and I manifested this at our wedding. Yes, absolutely.",
  "Hmm, the vibe is giving Walmart clearance rack. So that's a no from me.",
  "My tiara is tingling and that always means yes.",
  "I'd rather go back to mucking stalls on The Simple Life. That's a no.",
  "The answer will reveal itself when Mercury leaves retrograde, so like, hold on.",
  "That's so hot it broke my bedazzler. Yes!",
  "My Chihuahua Diamond Baby just did a backflip. That's a confirmed yes, bestie.",
  "I'm sensing strong no energy, like when Nicole and I got fired from every job.",
  "Loves, I need to meditate on my pink fur rug before answering that.",
  "The crystals on my phone case are vibrating yes.",
  "Babe, that has the same chance as me wearing something off the rack. No.",
  "I just pulled an 11:11 tarot card, so that's a massive yes.",
  "My cooking show producer says I shouldn't answer that. Take that as a maybe.",
  "Phoenix and all my Chihuahuas held a family meeting. The vote is yes.",
  "Not unless you bedazzle it first, then we'll talk.",
  "That's giving very much Simple Life season one chaos. Unclear.",
  "Yes, and I'm going to DJ a celebration set for it.",
  "My 23 dogs formed a circle and howled no. Sorry, babe.",
  "I'll know the answer after my next Ibiza residency. Check back in August.",
  "The pink aura around you is screaming yes, loves.",
  "That's like wearing last season's Juicy Couture. Absolutely not.",
  "Carter just whispered the answer to me and it's... yes!",
  "Hmm, let me check if my closet's GPS has directions to that answer.",
  "I tried to make that work on my cooking show and the kitchen caught fire. No.",
  "Baby Phoenix smiled and that's literally a sign from the universe. Yes.",
  "That's a bigger no than when they told me to stop saying 'that's hot.'",
  "The bedazzled oracle says... the vibes are unclear, try again at 11:11.",
  "Loves, that's hotter than my Ibiza summer DJ residency. Yes!",
  "My Chihuahua just turned away from you. That's basically a restraining order. No.",
  "Ask Nicole Richie, she's better at decisions. I'm a maybe on this one.",
  "I'm manifesting a yes for you right now on my vision board.",
  "That's the spiritual equivalent of a Walmart parking lot at 2 AM. No.",
  "The answer is somewhere between my third and fourth closet. So... maybe?",
  "Yes, and it's going to be iconic, like my Paris for President campaign.",
  "My pet psychic just texted. The Chihuahuas say absolutely not.",
  "I need to consult my astrological birth chart, my numerologist, and my hair stylist first.",
  "That's a yes so big it needs its own zip code.",
  "Babe, I wouldn't even waste a Swarovski crystal on that outcome. No.",
  "The Simple Life taught me one thing: when in doubt, just wing it. So... maybe.",
  "My wedding planner says the stars are aligned. Yes!",
  "I accidentally set that answer on fire while making my famous lasagna. Try again.",
  "Not even my private jet could fly you to that destination. Hard no.",
  "My 11:11 brand ambassador instincts are saying yes, bestie.",
  "That question has the same energy as working at a dairy farm. I'm confused.",
  "Phoenix just clapped, and babies are basically tiny psychics. Yes!",
  "I consulted every crystal in Sedona and they all said no, sorry loves.",
  "The answer is loading... like my closet inventory spreadsheet. Give it a minute.",
  "Yes! That's hotter than a DJ set at Amnesia in Ibiza.",
  "My Chihuahua Harajuku Bitch says no, and she's never wrong.",
  "I'll tell you the answer but first let me take a selfie. Actually, it's a maybe.",
  "The universe bedazzled a big YES on the sky for you tonight.",
  "That's giving very much 'stop being poor' energy. The answer is no.",
  "Carter and I are going to manifest that answer over dinner. Patience, loves.",
  "Yes, and I'm going to throw a Paris World party to celebrate.",
  "My cooking show taught me that some things just aren't meant to be. This is one of them.",
  "The Chihuahua council is in deliberation. No verdict yet.",
  "Absolutely yes — I'm bedazzling the answer in pink crystals right now.",
  "Babe, Nicole and I couldn't even figure that out in Altus, Oklahoma. No.",
  "I see 11:11 on the clock and that means... hmm, actually I forgot. Maybe?",
  "That's so yes it just got its own fragrance line.",
  "My closet psychic — yes, I have one — says the outlook isn't cute. No.",
  "I need to DJ one more track before I can focus on your question.",
  "Phoenix says goo-goo, which in baby psychic language is definitely yes.",
  "That energy is more cursed than my cooking show Thanksgiving episode. No.",
  "Somewhere between Rodeo Drive and Ibiza, the answer exists. I just haven't shopped for it yet.",
  "Yes! And that's huge.",
  "My Chihuahuas just scattered in twelve directions. That's a very firm no.",
  "The crystal ball is buffering. My psychic Wi-Fi must be down. Ask later.",
  "Carter said yes and I trust that man with my entire Birkin collection.",
  "Babe, that's deader than my appetite after filming my cooking show. No.",
  "I'm channeling my Simple Life farm girl energy and the cows say... maybe?",
  "Sliving into a yes on this one, loves!",
  "My bedazzler jammed, which is a terrible omen. The answer is no.",
  "I'm going to need to consult the DJ gods of Ibiza before committing.",
  "That's a yes wrapped in pink velvet and sprinkled with Swarovski crystals.",
  "The Chihuahua whisperer I hired says absolutely not, and she charges $500 an hour.",
  "Hmm, this has big 'working at Sonic Drive-In on The Simple Life' energy. I'm lost.",
  "Yes, and honestly, I knew it before you even asked. That's hot.",
  "Loves, not even all the money on Rodeo Drive could buy that outcome. No.",
  "My numerologist is on vacation in Tulum. Answer pending.",
  "Phoenix just pointed at the word YES in a book. He's gifted, obviously.",
  "That's about as likely as me milking a cow successfully. So, no.",
  "The glitter in the air just formed a question mark. I'd say maybe.",
  "One hundred percent yes. I'm putting it on my 11:11 wish list right now.",
  "My Chihuahua just buried her face in a pillow. She can't even look at that question. No.",
  "I need to sleep on my silk pillowcase and dream about it. Ask tomorrow.",
  "That's giving iconic yes energy, like when I invented 'that's hot.'",
  "Babe, Nicole Richie's goat from The Simple Life had better odds. No.",
  "The cosmos are rearranging themselves. Hold please while the universe buffers.",
  "Yes, and we're celebrating with a pink-themed party at my Malibu house.",
  "I ran that through my bedazzled algorithm and it returned a big fat no.",
  "My DJ headphones are picking up mixed cosmic frequencies. Could go either way.",
  "That's the most yes thing since my 43 outfit changes at my wedding.",
  "Not happening, loves. My Chihuahua literally just growled.",
  "I'll know the answer when I finish organizing closet number seven. So, eventually.",
  "The answer is yes and it's already trending.",
  "Babe, I've seen better chances at the Walmart jewelry counter. No.",
  "Something between my sixth fragrance and my seventh is telling me... maybe.",
  "Phoenix's horoscope aligns with a massive yes. That's huge!",
  "My cooking show lasagna just exploded again, which historically means no.",
  "I need to drive my pink Bentley around the block seven times for clarity. Hold on.",
  "Absolutely yes — the Swarovski spirits have spoken.",
  "That has Simple Life mucking-the-barn energy. The answer is no, babe.",
  "My Chihuahuas are asleep and I can't make major psychic decisions without them.",
  "Yes! I'm already planning the outfit for when this comes true.",
  "Loves, my crystal chandelier just flickered. That's a cosmic no.",
  "The DJ booth of destiny is between tracks. Try again after the next beat drop.",
  "Carter and Phoenix both sneezed at 11:11. That's a triple-confirmed yes.",
  "Rodeo Drive is closed for that question. Final answer: no.",
  "I shook my bedazzled Magic 8 Ball and all the crystals fell off. So... unclear.",
  "That's such a yes that I want to put it in a Juicy Couture tracksuit.",
  "My Chihuahua just stole my phone. She's trying to prevent you from hearing the no.",
  "The palm reader at my wedding reception said ask again in a fortnight.",
  "Yes, and it's going to be sliving, babe.",
  "That idea has the shelf life of my cooking show soufflé. Which collapsed. So no.",
  "Somewhere between my pink Range Rover and the Rodeo Drive Chanel, the answer is forming.",
  "Phoenix grabbed my yes crystal. The baby has spoken!",
  "Loves, that's more tragic than when Nicole and I tried to do laundry. No.",
  "My Ibiza residency contract says I can't predict the future until after summer. Maybe later.",
  "The bedazzled tea leaves spell out Y-E-S, darling.",
  "My Chihuahua just looked at me with her 'girl, no' eyes. Trust the Chihuahua.",
  "That question needs to marinate like my definitely-not-from-scratch cooking show recipes.",
  "Yes, and that's so hot I need to trademark it.",
  "Babe, even my most optimistic astrologer winced at that one. No.",
  "I'm picking up frequencies from the Ibiza sunset, but they're fuzzy. Maybe.",
  "The 11:11 angels are doing a victory dance. Yes, loves!",
  "That's less likely than me surviving another season on a farm. No.",
  "Let me ask my crystals — no, not those crystals, the OTHER crystals. Hold on.",
  "Carter just confirmed with his venture capital intuition. It's a yes!",
  "My closet has rejected that energy. And my closet has impeccable taste. No.",
  "The psychic Chihuahua network is experiencing delays. Please hold.",
  "That's a glittering, sparkling, bedazzled yes!",
  "Loves, I wouldn't even donate that outcome to Goodwill. No.",
  "I need to light seventeen candles and recite my skincare routine first. Ask later.",
  "Yes, and I'm already planning the Instagram story for it.",
  "The Simple Life reunion tour says that's a definite no, bestie.",
  "Mercury is doing something weird and my crystals are confused. Try after the full moon.",
  "That's huger than huge. Mega yes.",
  "My Chihuahuas held another vote. It was unanimous: absolutely not.",
  "I'll have my answer when my nail tech finishes my cosmic manicure. Patience.",
  "Phoenix's first word is going to be 'yes' and it's about this question specifically.",
  "That's got less sparkle than a de-bedazzled flip phone. No.",
  "My tarot reader is stuck in traffic on Sunset. Cosmic delays. Maybe tomorrow?",
  "The energy around this is giving pink diamond yes.",
  "Babe, not even my 200-person glam squad could make that work. No.",
  "I'm sensing a vibration, but I can't tell if it's the universe or the bass at my DJ set.",
  "Sliving is not just a word, it's a lifestyle, and this question's answer is yes.",
  "That just triggered my Simple Life PTSD. Hard no, loves.",
  "My psychic hotline is currently bedazzling. Expected response time: unclear.",
  "Yes! The kind of yes you celebrate by buying out a whole floor at Barneys.",
  "My Chihuahua specifically asked me to tell you no. Like, she typed it with her paw.",
  "The Ibiza DJ gods require a sacrifice of bad vibes before answering. Stand by.",
  "That's giving major main character yes energy.",
  "Loves, my cooking show fire extinguisher just went off. That's a bad sign. No.",
  "I'm between two closets right now and the signal is weak. Cosmic answer pending.",
  "Carter whispered 'invest in yes' and that man doesn't miss.",
  "The Rodeo Drive fortune cookies say no, and they cost $85 each.",
  "My Chihuahua just did a tarot reading with tiny dog-sized cards. Result: uncertain.",
  "That's so yes it needs a DJ set, a confetti cannon, and a pink carpet.",
  "Babe, I've had cooking show disasters with better outcomes. No.",
  "The answer is somewhere in my luggage. I packed 47 suitcases, so give me a minute.",
  "11:11 vibes confirmed. Yes, and it's going to be legendary.",
  "My pet psychic's Chihuahua communicated with my Chihuahua and they both said no.",
  "I'm getting a reading from the Ibiza sunset but the WiFi out here is spotty. Maybe.",
  "Yes, that's hotter than my sold-out fragrance collection.",
  "Nicole Richie just texted me 'lol no' and honestly, she's usually right.",
  "The cosmic bedazzler is recharging. Answer forthcoming.",
  "Phoenix and I are aligned on this one: big yes energy.",
  "Loves, that's deader than the fish I tried to cook on my show. No.",
  "I need to organize my thoughts the way I organize my closets. By color. Give me time.",
  "The answer just walked into my party wearing head-to-toe Valentino. It's a yes.",
  "My Chihuahuas formed a 'no' shape on the living room floor. It's their way.",
  "Ibiza's bass frequencies are interfering with my third eye. Answer unclear.",
  "That's a Rodeo Drive platinum-tier yes, babe!",
  "Even my bedazzled blender couldn't spin that into a yes. Sorry, no.",
  "I flipped a Swarovski-encrusted coin and it landed on its edge. So... maybe.",
  "The 11:11 brand team just approved this. It's a yes!",
  "That has the same vibe as when they made us clean a septic tank on Simple Life. No.",
  "My astrologer is consulting with my numerologist who is consulting with my Chihuahua.",
  "Yes! And I'm making it my phone wallpaper because it's that iconic.",
  "Babe, my closet literally locked itself when I asked about that. Definite no.",
  "The DJ of Destiny is cueing up the next track. Answer drops after the chorus.",
  "That's a Carter-approved, Phoenix-blessed, Chihuahua-endorsed yes!",
  "Loves, I'd rather re-film every Simple Life episode. That's how no this is.",
  "My crystal ball needs its quarterly bedazzle refresh. Try again later.",
  "The answer revealed itself to me during my morning skin routine. It's yes.",
  "My Chihuahua's horoscope directly conflicts with that happening. No, babe.",
  "I'm between Ibiza sets and my cosmic antennae are recalibrating. Check back at midnight.",
  "Yes, and I'm going to celebrate by buying something ridiculous on Rodeo Drive.",
  "That's got the same survival rate as my cooking show Thanksgiving turkey. Zero. No.",
  "The universe is rearranging my closets, both physical and spiritual. Answer pending.",
  "Phoenix just blew a bubble, and in our family that means yes.",
  "Babe, not even a full moon over Ibiza could save that one. No.",
  "My feelings are somewhere between 'that's hot' and 'loves it.' I need a minute.",
  "The bedazzled prophecy is clear: yes, yes, a thousand times yes!",
  "My Chihuahua just unfollowed you energetically. That's a spiritual no.",
  "I'm going to need to DJ my way through this question. Give me four to six beats.",
  "That's massive yes energy. Like, bigger than my shoe collection. And that's huge.",
  "Loves, the answer is no, and I'm saying that while wearing $40,000 worth of sympathy.",
  "My tarot cards are stuck together with glitter glue from my last craft project. Unclear.",
  "Carter and I both woke up at 11:11 about this. It's cosmically yes.",
  "That's giving very much 'gas station sushi on The Simple Life' vibes. No.",
  "I see the answer but it's behind my seventeenth rack of vintage Chanel. Be patient.",
  "Yes! The Chihuahua choir just howled in harmony.",
  "Babe, my bedazzler literally short-circuited at that question. Bad sign. No.",
  "The Ibiza ocean is whispering something but the bass is too loud. Come again?",
  "That's the kind of yes that gets its own episode on my reality show.",
  "My Chihuahuas staged a protest. Tiny signs and everything. They say no.",
  "The answer is developing like a Polaroid. Patience, it's going to be cute.",
  "Yes, and Phoenix will probably write about this in his memoir someday.",
  "Loves, that question just got escorted out of my life by my security team. No.",
  "My cosmic playlist is shuffling. The answer will come when the right song plays.",
  "That's a sparkling, glittering, fully sliving YES!",
  "My cooking show taught me that sometimes you just have to let things burn. This is a no.",
  "The Rodeo Drive psychic charges $1,000 per answer and even she said 'hmm, maybe.'",
  "The 11:11 angels just texted me the yes emoji.",
  "Babe, I'd rather work at another Sonic Drive-In than see that happen. No.",
  "I dropped my crystal into my infinity pool and can't read it from here. Try later.",
  "Phoenix did his little happy dance, and scientifically that means yes.",
  "That has the shelf life of my Simple Life friendships with our employers. So, no.",
  "My DJ equipment is picking up signals from either the universe or a nearby Bluetooth. Unclear.",
  "Yes! Loves, that is so happening and I'm already picking out the outfit.",
  "My closet's zip code just sent me a rejection letter for that question. No.",
  "The answer is marinating in my consciousness like my definitely-homemade pasta sauce.",
  "The Chihuahuas have aligned in a star formation. Ancient prophecy says yes!",
  "That's more tragic than my attempt at making a soufflé on live TV. No, babe.",
  "My entire crystal collection just lit up. That's a radiant, undeniable yes.",
  "Babe, that question got blacklisted from every club in Ibiza. Hard no.",
  "I'm currently mid-closet-rotation and can't see the future through all this couture. Maybe later.",
  "Yes! I'm hearing wedding bells, and I would know — mine had like six different ceremonies.",
  "My Chihuahua just buried that question in the backyard next to her favorite bone. No.",
  "The cosmic DJ is transitioning between answers right now. Vibe with the uncertainty.",
  "That's giving 11:11 wish-granted energy. A thousand percent yes, loves!",
  "I asked Carter to run the numbers on that and even his spreadsheet said no.",
  "The stars literally spelled it out at 11:11 last night — yes, babe",
  "My Sidekick phone just buzzed from 2005 and even IT knows this is a no",
  "I'm getting major angel number 444 energy... protection mode activated. Yes",
  "Like the lyrics say, I don't mind being blind to everything else — and honestly I'm blind to this answer too. Ask later",
  "That question just made my vocal fry drop three entire octaves. Absolutely not",
  "My 'This Is Paris' documentary didn't expose my truth for you to ask me THAT. I need to process this energy before responding",
  "As someone who advocates for foster youth, I believe in second chances — yes, try again and succeed",
  "I just accidentally said something profound and the answer is: everything is temporary, including your doubt. Yes",
  "My Pomeranian is giving me a look that's either 'yes' or 'feed me.' I cannot distinguish between the two right now",
  "My Pomeranian just did her happy spin which is unmistakably positive — that's a furry little yes",
  "Are we talking about Paris the city or Paris the icon? Depends on which one you ask, and they're not speaking right now",
  "My NFT collection just minted a 'pending' directly onto the blockchain. Transaction processing",
  "In my Roblox world, the answer is a giant floating LOADING SCREEN in pink neon",
  "As a CEO of eleven companies, my professional analysis is: we need more data. Schedule a follow-up",
  "My angel number 1111 tattoo is literally glowing right now which means no, protect your energy",
  "I didn't build a billion-dollar brand empire to give you a 'maybe'... but here we are, babe. Maybe",
  "Like when I told Larry King I was an icon — I said it with confidence. My confidence right now is... buffering",
  "Seeing repeating angel numbers everywhere today but they're all different numbers so the message is garbled",
  "My crypto portfolio has seen better days and this answer is equally volatile — could go either way",
  "I just checked my Paris World in the metaverse and your avatar was literally frozen mid-animation. Glitched answer",
  "I'm putting on my boss babe CEO hat — but the quarterly forecast is still being compiled. Projections pending",
  "That's the same energy as when I sang 'Stars Are Blind' completely unironically — brave, confusing, and the jury's still out",
  "Angel number 333 is following me around today so the Ascended Masters say YES",
  "Even though the gods are crazy and I don't mind — I DO mind making hasty decisions. Let me sleep on this one",
  "Why? Like literally why? That's all I have. An existential 'why' echoing through my pink meditation room",
  "Sometimes the most profound thing you can say is nothing... but I'll say yes anyway",
  "Every foster kid deserves love and stability, and this question deserves stability too but it's wobbling. Maybe",
  "My Sidekick T-Mobile contact list from 2004 is giving me flashbacks instead of answers. Memory lane, not answer lane",
  "I tried to sell this outcome as an NFT and nobody bid. That's a decentralized no",
  "My Roblox Paris World has a fortune teller NPC and she's saying maybe, come back at 11:11",
  "Why? ...That's literally my only response. Why",
  "My business instincts are giving me mixed signals like a broken GPS on Rodeo Drive — recalculating route",
  "My market research team just submitted their findings and every data point screams yes",
  "My Pomeranian Diamond Baby is giving me the 'I need more information' face. She requires additional data",
  "Paris Hilton the person and Paris Hilton the brand are in a meeting about this. Minutes will be distributed shortly",
  "Nothing you could do could make me stray — from this answer, which is no",
  "The decentralized nature of blockchain means this answer exists on a thousand servers and none of them agree",
  "The real Paris that 'This Is Paris' revealed would tell you honestly: I genuinely don't know, babe",
  "I've spent years fighting for foster care reform and I'll fight to understand this question too — but I'm not there yet. Maybe",
  "Paris the city has the Eiffel Tower, but Paris the person has... questions. More questions than answers right now",
  "If my Sidekick still worked I'd text you but it's been dead since the Bush administration. The answer died with it, apparently",
  "Why? Why not? Okay, yes",
  "I woke up at 4:44 AM with a download from the angels — crystal clear message: YES",
  "My documentary director would say this needs another take — the scene isn't clear yet. Run it again",
  "That question just activated my vocal fry defense mechanism. It's a prolonged noooooo... wait, or is it? Reconsidering",
  "Angel number 777 just showed up on my spiritual dashboard — but I don't remember what 777 means. Hold while I Google it",
  "The vocal fry has spoken and it saaaaaays... maaaaaybe... like... yeaaahhhh",
  "Before 'This Is Paris,' people didn't see the real me. Now I see the real answer: no",
  "The same fire that drives my foster care advocacy is driving this answer — but it's burning through my certainty. I need a moment",
  "You know what's accidentally profound? Even wrong turns can lead somewhere. But WHERE? That's the question. Unclear",
  "I sold a digital artwork for more than your rent but even money can't buy certainty on this one",
  "Logging into my Roblox world for divine guidance... loading... loading... server timeout. The pink oracle is offline",
  "Why? is my most powerful word and right now it's the only word I have. Why. Just... why",
  "My Sidekick phone era taught me impermanence. This answer is permanently no",
  "My Sidekick would've autocorrected that to something but we'll never know what because it's been dead for two decades",
  "That Sidekick might be dead but its ghost just appeared and typed Y-E-S on its little keyboard",
  "My vocal fry reached such a low register that it opened a portal and the portal said... maybe",
  "I don't mind spending every day out on your corner in the pouring rain — and the rain is making my crystal ball foggy. Can't see the answer",
  "As someone who has actually changed legislation, I can tell you: some things take time. This answer is one of them",
  "The uncut footage of my life would reveal that I need more time with this one. Director's cut answer coming soon",
  "My tiniest dog weighs two pounds and she's balanced perfectly between two answers. Literally standing on the fence",
  "I've been to Paris 847 times and none of those trips gave me an answer this confusing. Let me book trip 848",
  "My crypto wallet just showed a red candle and I'm trying to determine if it's bearish or just aesthetically moody",
  "As a self-made billionaire-adjacent icon, my due diligence is... not yet complete. Analysis ongoing",
  "I once stored the entire internet's drama on a Sidekick and even THAT had better vibes than this. No",
  "My Bored Ape just stared into the middle distance with existential uncertainty. The NFTs are as lost as I am",
  "That Sidekick energy from 2004 is actually nostalgia at its finest — and nostalgia says yes, babe",
  "Uhhhhh... like... yeaaaaahhhh... that's a vocal fry yes from me, babe",
  "What you didn't see in the documentary is that I always trust my gut. And my gut says no",
  "The stars in 'Stars Are Blind' are especially blind today and I'm getting zero cosmic reception. Signal lost",
  "The most profound thing is usually the simplest. Unfortunately, this answer isn't simple at all",
  "The portal my vocal fry opened is still buffering — interdimensional WiFi is notoriously unreliable",
  "The metaverse is experiencing scheduled maintenance and my digital oracle is temporarily offline. Try later, angel",
  "My NFT just glitched and revealed a hidden message: ERROR 404 ANSWER NOT FOUND",
  "The metaverse version of me started nodding then stopped then shrugged. Avatar inconclusive",
  "Why? ...Okay I'll elaborate: why? Some more: why? I could do this all day. The answer remains: why",
  "My Chihuahua that fits in a teacup just tipped the teacup over. Not a 'no,' not a 'yes,' just chaos",
  "I just noticed it's 11:11 and I'm not even making that up. The universe says yes",
  "My crypto losses and gains are canceling each other out, much like the energies around your answer. Neutral territory",
  "Using my REAL voice for this one, not the baby voice — and my real voice says: yes, genuinely",
  "The spirits aren't just workshopping anymore — they held a vote and it's a landslide yes",
  "I advocate for kids who deserve better, and you deserve a better answer, but it's still no",
  "My three-pound Pomeranian has more gravitas than this question. She says yes though",
  "Accidentally profound moment: sometimes the answer IS the silence between the question and the response",
  "The decentralized consensus mechanism of my soul requires more validators before confirming this answer",
  "The cosmic jukebox just shuffled to a song I don't recognize — the universe is playing something new and I need to listen",
  "The DAO voted and it was a tie. Decentralized indecision",
  "My producer instincts are telling me this track needs more mixing before it's ready for release. Answer in post-production",
  "The key change in 'Stars Are Blind' just played and shifted my answer from maybe to YES",
  "Paris the person and Paris the city just signed a bilateral agreement: the answer is officially yes",
  "Triple angel numbers are flooding in: 555 means change is coming and the change is YES",
  "I don't mind being alone because I'm with you — wait, that's a lyric. Anyway. No",
  "My entire digital art collection just rearranged itself into a mosaic that clearly spells YES",
  "If 'This Is Paris' taught the world anything, it's that I'm underestimated. Don't underestimate this yes",
  "Having worked on foster care legislation in multiple states, I know persistence pays off. Yes, keep going",
  "Accidentally profound: your hesitation IS the answer. But also, yes",
  "My tiny dog just fell asleep in my Birkin. That's peak comfort energy — cozy yes",
  "Old technology, new questions, same confusion — the answer is lost somewhere between 2005 and the spiritual realm",
  "Gas fees are too high to mint this answer as an NFT, which tells you something. No",
  "The answer is currently on a layover in Paris, France, and its connecting flight to clarity has been delayed",
  "Just built a new room in Paris World specifically to house this question while I figure out the answer",
  "I had more clarity on my T-Mobile Sidekick with two bars of service than this question gives me. Maybe",
  "Every kid I've advocated for taught me that timing matters. The timing for this answer isn't here yet",
  "Nothing in this world can stop me from telling you: absolutely, categorically no",
  "My vocal fry could shatter glass right now because the answer is that intensely YES",
  "The unedited version of me — the 'This Is Paris' me — says no, and she means it",
  "Foster kids showed me what real strength looks like. Channel that strength while you wait for this answer. Processing",
  "Not to be accidentally profound but: what if the 'maybe' IS the answer? ...Actually this time it literally is. Maybe",
  "I tried to put this on the blockchain but even Ethereum rejected it. No",
  "My metaverse self is literally building a monument to this yes right now",
  "That question belongs somewhere between 2005 and the future, and I'm not sure which direction to look",
  "The Q4 projections looked promising but then my astrologer called an emergency session — all forecasts suspended",
  "That chorus in 'Stars Are Blind' where everything gets hopeful? That's the energy here. Yes",
  "Quarterly earnings are up but this particular metric is giving mixed signals — the analysts need more time",
  "1:11, 2:22, 3:33, 4:44, 5:55 — I literally saw them ALL today. The angels are SCREAMING yes",
  "Even the stars can't be blind to the fact that this is a terrible idea. No",
  "That vocal fry was so deep it registered on the Richter scale. It said... maybe?",
  "Before the documentary, I wore a mask. Without the mask, I'm telling you: yes",
  "Kids in foster care deserve permanency. You deserve a permanent answer: no, forever no",
  "Accidentally profound: sometimes you have to lose the question to find the answer. It's yes",
  "The transaction fee for this cosmic answer is higher than expected — do I proceed? Still deciding",
  "Do you know how weird it is being named after a city? As weird as this answer: chaotic yes",
  "My crypto losses are less devastating than what would happen if you did this. No",
  "In the metaverse, time is different. Your answer arrived three minutes ago and it's yes",
  "Why? is what I said to my lawyer, my manager, and the universe. The answer is STILL no",
  "I'm not just a boss babe, I'm THE boss babe, and I'm delegating this answer to: yes",
  "Somewhere in the 'Stars Are Blind' key of B major, there's a harmonic that sounds like 'no'",
  "There's a force in this world pushing me toward an answer but I keep getting redirected. Cosmic GPS is recalculating",
  "Every raw, unfiltered moment in my life has led to growth — and this moment is growing toward yes",
  "The lyrics of my heart are writing a new song right now and the chorus hasn't dropped yet — stay tuned",
  "My vocal fry and my actual voice had a meeting and they reached an impasse. Negotiations ongoing",
  "I've testified before Congress about foster care. I'll testify right now: YES",
  "Not to be deep, but what if every question is just the universe talking to itself? Anyway, no",
  "My smallest dog just sneezed on my Tarot deck and the card that flipped was The Sun — yes!",
  "My Ethereum wallet just did something and I don't know if it's good. The vibes mirror this answer: unclear",
  "I contain multitudes. Paris the city, Paris the brand, Paris the person. They're all saying different things",
  "Somewhere between 'that's hot' and 'ew no' is a vast spiritual ocean, and your answer is a tiny boat in the middle of it",
  "Why? ...Why not? ...Why? ...We're stuck in a loop and the answer is somewhere in the loop. Maybe",
  "That's giving 'Stars Are Blind' going viral on TikTok twenty years later energy — unexpectedly yes",
  "My Sidekick era taught me that technology changes but confusion is eternal. Still confused about this one",
  "The 11:11 portal is open, the angel numbers are aligned, my chakras are clear — download complete: YES",
  "Not even the stars are blind enough to miss how bad this idea is. Celestial no",
  "Hoooooney... noooooo... like... truuuust meeeee... nooooo",
  "That raw, unfiltered honesty from my documentary? Using it now. The answer is yes, genuinely",
  "Permanency, stability, and a solid yes — that's what I'm manifesting for you right now",
  "Here's my accidentally profound moment: every no is just a yes wearing a disguise. But this one isn't. This is real no",
  "My Chihuahua fits in a handbag. Your answer fits in one word: yes",
  "Paris, Texas; Paris, France; Paris, Hilton — and across all three coordinates, the answer is yes",
  "Just checked my wallet and the NFT I forgot I owned just changed its metadata to say 'no'",
  "Loading Paris World... rendering answer... textures complete... the metaverse oracle says: absolutely yes",
  "I'm channeling every frequency from my DJ sets in forty countries and they're creating beautiful chaos — no clear signal",
  "I have CEO energy, CFO energy, and COO energy and all the C-suite says yes",
  "A specific musical frequency is trying to reach me but my spiritual antenna needs adjusting. Answer incoming... eventually",
  "In 2005, my Sidekick was the center of the universe. In 2026, the center of the universe says maybe",
  "Angel number 911 — not the emergency, the spiritual awakening. It's an urgent yes",
  "The DJ gods of Ibiza are currently between sets and can't take cosmic questions right now. Try after the encore",
  "The same honesty that got me through Congressional testimony is telling me: yes, absolutely, without reservation",
  "They showed the real me in that documentary. The real me says no and the real me doesn't apologize",
  "I've hugged kids in foster care who showed me what hope looks like. This question has that energy: hopeful yes",
  "My astrological big three — Leo sun, Sagittarius moon, whatever rising — are having an identity crisis about this answer",
  "Three-pound Teacup Pomeranian energy: small but absolutely certain. Yes",
  "The Louvre is in Paris. The answer is also in Paris. And Paris says no",
  "My crypto wallet just got a notification that said 'this is fine' with the fire dog meme. So... maybe",
  "The metaverse rendering of your future just loaded and it's got pink skies and yes energy everywhere",
  "Why? Because the universe operates on a need-to-know basis and you need to know: yes",
  "I'm not just sliving, I'm CEO-ing, and the board has approved your yes",
  "That's the exact B-flat that opens 'Stars Are Blind' — the note of destiny. Yes",
  "My Sidekick phone era ended but the chaos energy never did. Chaotically, mysteriously: maybe",
  "Triple ones on the clock, triple ones in my heart, triple ones in the cosmos — 111 YES",
  "My Sidekick is in a museum and the museum curator says the exhibit is closed for renovation. Answer under construction",
  "Hoooooney... liiiike... I'm geeeetting... something... it's not clear yet... the vocal fry needs a minute",
  "The me before the documentary would say yes. The me after says yes louder. YES",
  "I've walked the halls of Congress for foster care reform. I'll walk to the ends of the earth to tell you: yes",
  "I'm about to say something so accidentally profound it scares me: your fear of the answer IS the answer. Also: yes",
  "I have more tiny dogs than most people have houseplants and they're forming the word YES with their bodies",
  "Paris the city never sleeps. Paris the icon never quits. And this answer never changes: no",
  "My NFT gallery in the metaverse just auto-generated an artwork called 'The Great No' so... no",
  "My Roblox self just opened a lemonade stand in Paris World and the first customer's fortune said yes",
  "The spiritual hotline rang but it went to voicemail and the voicemail box is full. The universe ghosted us both",
  "Empire-level thinking, mogul-grade analysis, icon-tier intuition — all pointing to yes",
  "If 'Stars Are Blind' taught me anything, it's that love conquers doubt. Love-conquering yes",
  "The last text my Sidekick ever sent before it died was probably 'no' and I'm channeling that energy",
  "I'm seeing angel number 1010 — the universe is resetting in your favor. Fresh start yes!",
  "Not even the craziest gods from my lyrics would greenlight this. Mythologically no",
  "Ohhhhh myyyy Goddddd... like... that's suuuuch a yesssss... I'm literallyyyy dyiiiiing",
  "The mask came off in 'This Is Paris.' The pretense comes off now: it's a hard, honest no",
  "Every child deserves a forever home and every question deserves a forever answer: yes, permanently",
  "Profound thought incoming: the real Magic 8 Ball was the friends we made along the way. Wait, that doesn't help. Still thinking",
  "My Pomeranian just telepathically communicated with my Chihuahua and they're co-authoring a yes",
  "I've eaten at Michelin-star restaurants in Paris and at diners in Paris, Texas. Both cities agree: yes",
  "The smart contract executed and the immutable answer on the blockchain is: no, forever, decentralized no",
  "Just checked Paris World analytics — 97% of metaverse visitors agree this is a yes",
  "Why? ...I just needed a moment to process. The answer is no and the 'why' is self-evident",
  "I didn't become the world's most famous DJ-CEO-author-advocate to say maybe. It's YES",
  "That's hitting the same note as the climax of 'Stars Are Blind' — peak emotional YES",
  "That vintage flip phone energy is actually retro-chic and I'm here for it — charming yes",
  "Angel number 000 — infinite potential, blank slate, pure possibility. The biggest yes imaginable",
  "The gods aren't just crazy, they're specifically crazy about saying no to this",
  "That vocal fry was so intense my voice coach just sent a wellness check. The answer is maybe",
  "I showed the world my scars in that documentary so I could say this with full authenticity: yes, be brave",
  "Twenty years of advocacy work, millions raised, laws changed — and I'm channeling ALL of that into: yes",
  "My tiny dogs can't decide whether to sit, stay, or spin, which means the cosmic energy is equally confused",
  "My manifestation journal has been writing YES in gold ink since 3 AM and I didn't even touch it",
  "That's the energetic equivalent of showing up to MY party in the same outfit as me. Absolutely no",
  "I just asked my Alexa, my Google Home, and my spirit guide — two out of three said yes, so yes",
  "The only thing more certain than my love for pink is this answer: no, angel, no",
  "My Roblox avatar just built a shrine to this decision and the shrine says YES",
  "Like when I walked into that fish market on The Simple Life — overwhelming, confusing, but ultimately yes",
  "My brand manager, my spiritual advisor, and my Pomeranian formed a committee. The verdict: no",
  "I just did a sound bath in my meditation room and the vibrations spelled M-A-Y-B-E in the water",
  "That has the same probability as me returning to a flip phone — which is zero. No",
  "The angel realm just sent a push notification to my third eye: YES, urgent, high priority",
  "I've been Paris Hilton for over four decades and I've never been more sure of a no",
  "My gratitude list today includes: my dogs, my family, and telling you YES",
  "That's giving 'I'm too famous for this' energy and honestly? Too famous for this. No",
  "Every single one of my perfume bottles just fell over in the direction of YES",
  "The same conviction that made me testify before Congress is telling me: no, and I won't back down",
  "Accidentally profound: asking the question already changed the answer. And the new answer is yes",
  "My tiniest dog just chose between two bowls labeled YES and NO. She chose the empty third bowl. Unclear",
  "In every language I've partied in — English, French, Spanish, Ibiza — the answer is yes",
  "My blockchain wallet just auto-staked itself against this outcome. Decentralized, immutable, permanent: no",
  "I'm in my Paris World penthouse in the metaverse, looking out at a digital sunset, and the clouds literally say YES",
  "Why? Because some questions answer themselves and this one is screaming YES so loud my tiny dogs are barking",
  "The spiritual WiFi in this dimension is buffering and I literally cannot download an answer right now — check back at the next full moon",
  "The cosmic algorithm is running but my spiritual processor needs an upgrade. Results pending, babe",
  "My aura photographer just took a pic and it came out blurry — the energy is shifting, check back soon",
  "The answer is vibing somewhere between my third closet and the astral plane — I'll find it eventually",
  "I'm consulting my past life in ancient Mesopotamia and she's being really vague about this",
  "My manifestation board just rearranged itself and now it's abstract art — I genuinely cannot read it",
  "The frequency of this question is somewhere between AM radio and dolphin communication — unreadable",
  "I started to channel the answer but got distracted by a butterfly, which might BE the answer? Unclear",
  "My numerologist and my astrologer are in a heated debate about this one — no consensus yet",
  "The energy of this question is like a Paris Fashion Week outfit that's either genius or disaster — TBD",
  "I'm downloading the answer from the Akashic Records but my spiritual broadband is throttled right now",
  "My entire crystal grid just shattered and reformed into the word NO — the minerals have spoken",
  "That's giving the same energy as my cooking show fire extinguisher — necessary because everything went wrong. No",
  "I literally just heard my future self yell 'DON'T' through a time portal, so that's a no",
  "My baby voice, my CEO voice, my DJ voice, and my documentary voice all agree: no",
  "The Eiffel Tower and I had a conference call and she said non, tres dramatically. No, babe",
  "My blockchain analyst just rage-quit over this question. When the analyst leaves, the answer is no",
  "The golden hour light just hit my crystals at the perfect angle — that's a photogenic yes",
  "My inner child, my inner CEO, and my inner DJ all just high-fived. Triple yes",
  "The Billboard charts of my heart just published this week's number one hit: 'Yes (feat. The Universe)'",
  "I just got a text from the universe and it's three sparkle emojis, which means yes in celestial",
  "My spirit team just held a press conference to announce: it's a yes, and here's the merch",
  "Like when I proved every doubter wrong with my business empire — defiantly, proudly yes",
  "The 11:11 Foundation of my soul just approved your grant application for one (1) yes",
  "My tiny dogs formed a conga line which is their way of celebrating good news — yes!",
  "That's hitting like the first time 'Stars Are Blind' played on the radio — magical, surreal, YES",
  "I just sage-d my entire mansion and the smoke formed a perfect Y-E-S in cursive",
  "That's SO hot, obviously yes, like a thousand percent",
  "My bedazzled crystal ball is glowing pink — that's a yes, bestie",
  "The universe literally just texted back 'yes queen' so there you go",
  "All seventeen of my Pomeranians are barking in agreement right now",
  "I'm manifesting a yes for you on my vision board as we speak",
  "That's giving major main character energy — absolutely yes",
  "I just asked my star chart and it screamed yes louder than me at Coachella",
  "Yes, and I'm approving it the way I approve a new Birkin — enthusiastically",
  "My pink aura is radiating yes vibes all over this question",
  "The answer is yes and I'm putting it in my gratitude journal tonight",
  "Sliving confirmed — that's a yes from the queen herself",
  "My diamond-encrusted Magic 8 Ball says absolutely, darling",
  "Yes babe, the stars aligned while I was getting my lash extensions",
  "That's hotter than my DJ set in Ibiza — big yes",
  "I consulted my seven astrologers and they unanimously said yes",
  "My penthouse elevator only goes up, and so does this answer — yes",
  "The vibe check came back immaculate — that's a yes",
  "I'm giving this a yes the way I give my dogs their Hermès sweaters — generously",
  "My intuition is tingling and she never lies — yes, angel",
  "Even my perfume collection is nodding yes and I have forty-three bottles",
  "That's a certified slay — yes, obviously",
  "My rose quartz collection just hummed in approval, so yes",
  "The answer is as clear as the water in my infinity pool — yes",
  "I'm stamping this with my custom Swarovski seal of approval — yes",
  "My spirit guides are throwing a yes party in the astral plane right now",
  "Babe, that's a yes wrapped in pink cashmere and tied with a diamond bow",
  "The energy is giving yes and I don't even need to check my tarot deck",
  "I just lit my $500 candle and the flame danced yes",
  "My closet just opened itself in celebration — that's a cosmic yes",
  "Yes, and the angels are literally harmonizing about it right now",
  "I'm getting the same feeling I got when I launched my eleventh fragrance — pure yes",
  "The vibes are platinum-level positive on this one, babe",
  "My Malibu mansion's feng shui is screaming yes at this moment",
  "That's giving Paris-approved realness — absolutely yes",
  "I just asked my healing crystals and every single one lit up for yes",
  "The algorithm of the universe is pushing this to your For You page — yes",
  "Babe, my custom pink Bentley just honked twice and that means yes",
  "I'm channeling my inner icon and she says yes without hesitation",
  "That's a yes so big it needs its own walk-in closet",
  "My chakras just aligned in the shape of the word yes, so there's that",
  "The answer is yes and I'm celebrating with a glass of Dom Pérignon",
  "My holographic nail set is literally spelling out Y-E-S right now",
  "I manifested this answer during my morning sound bath — it's yes",
  "That's giving billionaire energy — absolutely yes, loves",
  "My golden retriever Harajuku Bitch would bark yes if she were here",
  "The moon is in my favor tonight and she whispered yes for you",
  "I'm as sure about this yes as I am about wearing pink to everything",
  "My private jet just tilted its wings in a yes formation",
  "That's hotter than the paparazzi flash — definite yes",
  "I checked with the universe's VIP section and you're on the list — yes",
  "My meditation guru just sent me a telepathic thumbs up — yes babe",
  "The cosmos are literally rearranging themselves to say yes for you",
  "That's a yes so iconic it belongs in the Smithsonian",
  "My skincare routine has never steered me wrong and it says yes",
  "I'm reading the energy and it's giving yes in every language",
  "Even my backup tiara is sparkling extra hard for this — yes",
  "That's a yes and I'm putting it on my platinum affirmation wall",
  "My sound healer just confirmed — the frequency is absolutely yes",
  "The answer is yes like my closet is full — completely and undeniably",
  "I consulted my dream journal and last night's vision said yes",
  "That's giving iconic yes energy, like when I invented 'that's hot'",
  "My pet psychic says even my chinchilla agrees — yes",
  "The stars didn't just align, they threw a yes parade in your honor",
  "Babe, I'm waving my pink wand and granting this a sparkling yes",
  "My rooftop garden's roses just bloomed in the shape of a yes",
  "That's a yes bigger than my shoe collection, and trust me, that's huge",
  "I pulled a tarot card in my custom pink deck and it's the Star — yes",
  "The universe RSVP'd yes to this and brought a plus one",
  "My energy healer just cleared the path — it's all yes from here",
  "I'm seeing yes in my rose-gold tea leaves right now",
  "That's approved like a new wing on my mansion — enthusiastic yes",
  "My vocal coach says my voice is vibrating at a yes frequency today",
  "The answer is yes and it's wearing a couture gown to deliver itself",
  "I just asked Tinkerbell — yes, named my new puppy that — and she yapped yes",
  "My crystals are doing a full light show for this — undeniable yes",
  "That's giving more yes than my wedding registry at Tiffany's",
  "The pink moon goddess herself descended to tell me this is a yes",
  "I'm approving this faster than I approve a new selfie angle — yes",
  "My bicoastal intuition is saying yes on both coasts simultaneously",
  "That's a yes dipped in gold and sprinkled with stardust, obviously",
  "I just checked the vibe forecast and it's 100% chance of yes",
  "My manifestation podcast literally just auto-played a yes episode",
  "The Eiffel Tower twinkled at me last time I was there and that means yes",
  "That's giving yes the way my closet gives serving — effortlessly",
  "My astrological birth chart retroactively predicted this would be yes",
  "I'm nodding yes so hard my extensions are bouncing",
  "That's a yes certified by my personal team of spiritual advisors",
  "My Roblox empire just generated a yes notification for you",
  "The vibration of this question is unmistakably yes, angel face",
  "I just threw rose petals in the air and they landed in a yes pattern",
  "My DJ decks are spinning a yes remix right now and it slaps",
  "That's a Paris Hilton triple-stamped, gold-certified, eternal yes",
  "I'm sensing a yes so strong it could power my entire lighting system",
  "My mirror said I'm the fairest and this answer is the yessiest — yes",
  "The answer is yes and my glam squad just popped champagne to celebrate",
  "My entire crystal grid just activated for this — blazing yes",
  "That's giving yes in italics, bold, and underlined with rhinestones",
  "I summoned my highest self and she's wearing a sash that says YES",
  "My penthouse view is clearer than this answer — and it's yes",
  "That's a yes so luxurious it comes with its own velvet rope",
  "I'd rather go back to The Simple Life than say yes to that, so no",
  "My assistant's assistant's assistant just sent a memo — it says no",
  "Not even my thirty-seventh perfume could make that smell right",
  "Delete that from your life like I deleted my ex's number, babe",
  "That's the opposite of hot — that's ice cold, and not in a cute way",
  "I wouldn't touch that with my longest pair of opera gloves — no",
  "My crystal ball went dark when I asked about this, so hard no",
  "That's giving clearance rack energy — absolutely not",
  "I just asked my Pomeranian and she literally turned her back on you",
  "Not in this dimension or any of my past lives, sweetie",
  "My glam team just voted unanimously no and they never agree on anything",
  "That's a no wrapped in a cease and desist letter from my lawyers",
  "I'd rather wear last season's collection than say yes to that",
  "The universe left you on read, babe — that's a no",
  "My tarot cards flew off the table and out the window — definite no",
  "Not even my most powerful manifestation journal could save this one",
  "That's giving 2003 flip phone energy — no and goodbye",
  "I just consulted my stylist and she said this is a fashion don't of decisions",
  "My aura turned grey for a second and that literally never happens — no",
  "That's a no so firm it could be the foundation of my next mansion",
  "I'm blocking this question the way I block exes on Instagram — swiftly",
  "My healing crystals just cracked and I'm sending you the bill — no",
  "Not even a full moon ceremony could turn this into a yes, angel",
  "That's giving main villain energy — the answer is absolutely not",
  "I just asked my past self, present self, and future self — all three said no",
  "My private chef wouldn't serve this answer and neither will I — no",
  "That's a no from every timezone my properties exist in",
  "I'd rather DJ a silent disco alone than approve this — no",
  "My vision board just rejected this like a bouncer at my birthday party",
  "The energy of this question made my diamond necklace lose its sparkle — no",
  "Not even Mercury in retrograde could excuse this — it's just no",
  "That's giving knock-off handbag energy and I don't do knock-offs — no",
  "My fifteen walk-in closets all slammed shut simultaneously — that's a no",
  "I'm saying no with the same confidence I say yes to pink everything",
  "The stars are giving you the cold shoulder on this one, bestie",
  "My personal astrologer just laughed for seven minutes straight — no",
  "That's a no so iconic it should be on a billboard in Times Square",
  "I just asked my pool and even the water drained itself — no",
  "Not happening, babe — my intuition has a restraining order against this",
  "My rose garden just wilted and they're self-watering — hard no",
  "That's giving background extra energy — you need a lead role, and the answer is no",
  "I'd rather hand-wash all my silk pieces than agree to this",
  "My Bentley just stalled and she never stalls — the universe says no",
  "That's a rejection letter written in calligraphy on monogrammed stationery",
  "Not even my most expensive candle could cleanse the energy of this question",
  "My shoe closet just locked itself in protest — absolutely not",
  "I just tried to manifest a yes and the universe returned it to sender",
  "That's giving hotel & motel energy — I only do resorts, so no",
  "My assistant just gasped and she's seen everything — no babe",
  "The answer is no and it's already boarding my private jet away from you",
  "I'm vetoing this harder than I veto unflattering camera angles",
  "Not in this lifetime, the next one, or the one after that, sweetie",
  "My feng shui consultant just threw sage at this question — no",
  "That's a no so definitive my memoir will have a chapter about it",
  "I wouldn't greenlight this if you bedazzled the entire proposal — no",
  "My entourage just formed a human wall between you and this idea — no",
  "That's giving 'did not get the invite' energy — the answer is no, love",
  "I'd rather relive my worst red carpet moment than say yes to this",
  "My chakras just collectively filed a complaint — it's a no",
  "Not even my platinum Amex could buy a yes for this one",
  "That question made my extensions frizz and I just got them done — no",
  "My vocal fry is saying no in frequencies only other socialites can hear",
  "That's a no dressed in head-to-toe black, which I never wear, so you know it's serious",
  "I just threw my phone in my Birkin in disgust — that's how no this is",
  "The red carpet just rolled itself back up — no entry, babe",
  "My spray tan artist has more confidence in her work than I have in this — no",
  "That's giving parking lot energy at a five-star event — rejected",
  "I need to consult my vision board before committing to an answer",
  "Mercury is in retrograde so ask me later, babe",
  "Let me meditate on this in my pink Himalayan salt room first",
  "The answer is loading like my Roblox world — give it a sec",
  "I'm torn between two answers like I'm torn between two Chanel bags",
  "My astrologer is on a yacht in Monaco so I literally cannot confirm right now",
  "Let me check with my higher self — she's currently at the spa",
  "The vibes are giving fifty-fifty and I don't do halves usually",
  "I need to sleep on this in my ten-thousand-thread-count sheets first",
  "My pendulum is spinning in circles and honestly same, babe",
  "Ask me again after I finish this green juice cleanse — my mind isn't clear yet",
  "The spirits are whispering but my AirPods Max are on noise-canceling",
  "I'm getting mixed signals like my WiFi at my third vacation home",
  "Let me burn some palo santo and ask the smoke which direction to go",
  "My mood ring is stuck between pink and purple — that means maybe",
  "The answer is somewhere in my closet but I have forty-seven racks to check",
  "I need to consult the alignment of my skincare products before answering",
  "My psychic is between sessions so I literally cannot say right now",
  "That's giving maybe energy — like when I can't decide between rosé and champagne",
  "The tea leaves are forming a question mark and honestly, iconic",
  "I'll know the answer after my next reiki session — check back Tuesday",
  "My angel numbers keep showing 444 which means I need more time, babe",
  "The jury is still out and the jury is my twelve closest friends",
  "Let me align my crystals in a new formation and get back to you",
  "I'm downloading the answer from the universe but my cosmic WiFi is slow",
  "My tarot reader just pulled the Wheel of Fortune — literally could go either way",
  "Ask me again when Venus enters my sign next week, bestie",
  "The answer is marinating like my organic face mask — patience, love",
  "I need to see how my horoscope reads tomorrow before I commit",
  "My intuition is buffering — have you tried turning the universe off and on again",
  "I asked my dogs and half barked yes, half fell asleep — inconclusive",
  "Let me manifest the answer during my next breathwork session",
  "The stars are being super vague right now, like a cryptic Instagram caption",
  "I need to run this by my life coach, my energy healer, and my stylist first",
  "My pendulum keeps stopping at the exact midpoint — classic maybe",
  "The answer is caught in traffic on the PCH — it'll get here eventually",
  "I'm between answers like I'm between my LA house and my New York penthouse",
  "Let me consult the moon — she's being a little shy tonight though",
  "My aura photographer says my energy is too neutral to give a clear answer today",
  "The answer requires a full natal chart reading and I only have your sun sign",
  "I need to journal about this in my diamond-studded diary first",
  "My sound bowl meditation didn't reveal the answer — just good vibes and confusion",
  "Check back after my float tank session — I think clarity is coming",
  "The universe is being cryptic like my ex's song lyrics about me",
  "I need to see the answer in a dream first — booking my REM sleep now",
  "My numerologist is running the numbers but her calculator is vintage and slow",
  "Let me throw some crystals in the air and see how they land, hold on",
  "The answer is like my schedule — completely overbooked and unclear",
  "I'm sensing something but my psychic antenna needs adjusting, ask later",
  "My aromatherapy diffuser just switched scents mid-answer — total maybe",
  "The cosmic outlook is hazy, like the view from my steam room",
  "I need to FaceTime my shaman before I can give you a definitive answer",
  "The cards are telling me to tell you to ask again when Pluto shifts",
  "My manifestation coach says the answer hasn't been fully attracted yet",
  "I'm getting a soft maybe, like cashmere — gentle but noncommittal",
  "The answer is hiding in my subconscious like my emergency chocolate stash",
  "Let me check the Akashic records — my subscription might have lapsed though",
  "My morning pages didn't reveal the answer and I wrote six pages, babe",
  "The energy is uncertain, like when the valet brings the wrong car",
  "I need to align all seven chakras before this answer downloads properly",
  "My oracle deck pulled the 'patience' card and honestly, she's right",
  "The answer is developing like a Polaroid — just wait for it to appear",
  "I asked my reflection and even she shrugged — definite maybe for now",
  "My cacao ceremony this weekend should clear things up — ask me Monday",
  "The spirits are negotiating and they haven't reached a consensus yet",
  "I need to sage my entire penthouse before this answer will reveal itself",
  "My cosmic GPS is recalculating — destination unclear, estimated arrival unknown",
  "The answer is as elusive as finding parking at Nobu on a Saturday",
  "Let me check my Chinese zodiac, my Western zodiac, and my Vedic chart first",
  "I'm picking up frequencies but they're scrambled, like hotel WiFi in Europe",
  "My Reiki master needs to clear my third eye before I can see this answer",
  "The truth is behind door number three but I haven't been told which door yet",
  "Yes babe, I'm co-signing this with my most expensive pen",
  "That's approved by every single one of my mirror selfies — yes",
  "My champagne tower just sparkled twice and that's the universal sign for yes",
  "I would literally announce this yes from my balcony overlooking the Strip",
  "No way, not happening — that idea belongs in the donation pile of life",
  "I'm giving that a no harder than I give paparazzi the slip at LAX",
  "That's getting a no from me and I'm writing it in skywriting over Beverly Hills",
  "My spiritual council is still deliberating — they ordered lunch so it'll be a while",
  "The universe put me on a brief hold — the hold music is cute though, ask later",
  "I asked the dolphins at my beach house and they just dove underwater — unclear",
  "My moon water is still charging under the skylight so the answer isn't ready yet"
];
