const PARIS_RESPONSES = [
  "That's hot.",
  "Loves it.",
  "Ew, no.",
  "That's not hot.",
  "Sliving! Yes!",
  "I'm too busy for this.",
  "Yas.",
  "Ask my assistant.",
  "Sanasa!",
  "That's huge.",
  "Yas Girl!",
  "Obviously.",
  "So cute.",
  "I die.",
  "Stop it.",
  "Obsessed.",
  "As if.",
  "Don't be jealous.",
  "Whatever.",
  "So yesterday.",
  "Not cute.",
  "Love that for you.",
  "It's a vibe.",
  "IYKYK.",
  "Literally dying."
];
